services:

  frigate-share:
    image: "ghcr.io/jleagle/frigate-share:main"
    container_name: "frigate-share"
    hostname: "frigate-share"
    restart: "unless-stopped"
    ports:
      - "5002:5002"

  radarr-share:
    image: "ghcr.io/jleagle/radarr-share:main"
    container_name: "radarr-share"
    hostname: "radarr-share"
    restart: "unless-stopped"
    entrypoint: "/root/radarr-share -radarr-key ${RADARR_KEY}"
    ports:
      - "7879:7879"

  sonarr-share:
    image: "ghcr.io/jleagle/sonarr-share:main"
    container_name: "sonarr-share"
    hostname: "sonarr-share"
    restart: "unless-stopped"
    entrypoint: "/root/sonarr-share -sonarr-key ${SONARR_KEY}"
    ports:
      - "8990:8990"
