global:
  sendAnonymousUsage: false

log:
  level: "INFO"

api:
  insecure: false
  dashboard: false

accessLog: { }

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: "websecure"
          scheme: "https"
          permanent: true
  websecure:
    address: ":443"

providers:
  file:
    filename: "/etc/traefik/providers.yml"
    watch: true

certificatesResolvers:
  myresolver:
    acme:
      storage: "/acme.json"
      email: "jimeagle@gmail.com"
      dnsChallenge:
        provider: "cloudflare"
        delayBeforeCheck: 10
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"
