# Learn more at https://github.com/jakowenko/double-take/#configuration
auth: false

# enable mqtt subscribing and publishing (default: shown below)
mqtt:
  host: 192.168.0.7
  client_id: doubletake

# frigate settings (default: shown below)
frigate:
  url: http://frigate:5000
  labels:
    - person
    - dog

  attempts:
    # number of times double take will request a frigate latest.jpg for facial recognition
    latest: 10
    # number of times double take will request a frigate snapshot.jpg for facial recognition
    snapshot: 10
    # process frigate images from frigate/+/person/snapshot topics
    mqtt: true
    # add a delay expressed in seconds between each detection loop
    delay: 0

  image:
    # height of frigate image passed for facial recognition
    height: 500

  # only process images from specific cameras
  cameras:
  # - front-door
  # - garage

  # only process images from specific zones
  zones:
  # - camera: garage
  #   zone: driveway

  # override frigate attempts and image per camera
  events:
  # front-door:
  #   attempts:
  #     # number of times double take will request a frigate latest.jpg for facial recognition
  #     latest: 5
  #     # number of times double take will request a frigate snapshot.jpg for facial recognition
  #     snapshot: 5
  #     # process frigate images from frigate/<camera-name>/person/snapshot topic
  #     mqtt: false
  #     # add a delay expressed in seconds between each detection loop
  #     delay: 1

  #   image:
  #     # height of frigate image passed for facial recognition (only if using default latest.jpg and snapshot.jpg)
  #     height: 1000
  #     # custom image that will be used in place of latest.jpg
  #     latest: http://camera-url.com/image.jpg
  #     # custom image that will be used in place of snapshot.jpg
  #     snapshot: http://camera-url.com/image.jpg

# camera settings (default: shown below)
cameras:
  front-door:
  # apply masks before processing image
  # masks:
  #   # list of x,y coordinates to define the polygon of the zone
  #   coordinates:
  #     - 1920,0,1920,328,1638,305,1646,0
  #   # show the mask on the final saved image (helpful for debugging)
  #   visible: false
  #   # size of camera stream used in resizing masks
  #   size: 1920x1080

  # override global detect variables per camera
  # detect:
  #   match:
  #     # save match images
  #     save: true
  #     # include base64 encoded string in api results and mqtt messages
  #     # options: true, false, box
  #     base64: false
  #     # minimum confidence needed to consider a result a match
  #     confidence: 60
  #     # minimum area in pixels to consider a result a match
  #     min_area: 10000

  #   unknown:
  #     # save unknown images
  #     save: true
  #     # include base64 encoded string in api results and mqtt messages
  #     # options: true, false, box
  #     base64: false
  #     # minimum confidence needed before classifying a match name as unknown
  #     confidence: 40
  #     # minimum area in pixels to keep an unknown result
  #     min_area: 0

  # snapshot:
  #   # process any jpeg encoded mqtt topic for facial recognition
  #   topic:
  #   # process any http image for facial recognition
  #   url:

# detector settings (default: shown below)
detectors:
  compreface:
    url:
    # recognition api key
    key:
    # number of seconds before the request times out and is aborted
    timeout: 15
    # minimum required confidence that a recognized face is actually a face
    # value is between 0.0 and 1.0
    det_prob_threshold: 0.8
    # comma-separated slugs of face plugins
    # https://github.com/exadel-inc/CompreFace/blob/master/docs/Face-services-and-plugins.md)
    # face_plugins: mask,gender,age

  deepstack:
    url:
    key:
    # number of seconds before the request times out and is aborted
    timeout: 15

  facebox:
    url:
    # number of seconds before the request times out and is aborted
    timeout: 15

# schedule settings (default: shown below)
schedule:
  # disable recognition if conditions are met
  disable:
  # - days:
  #     - monday
  #     - tuesday
  #   times:
  #     - 20:00-23:59
  #   cameras:
  #     - office
  # - days:
  #     - tuesday
  #     - wednesday
  #   times:
  #     - 13:00-15:00
  #     - 18:00-20:00
  #   cameras:
  #     - living-room

# notify settings (default: shown below)
notify:
  gotify:
    url:
    token:
    priority: 5

    # only notify from specific cameras
    # cameras:
    #   - front-door
    #   - garage

    # only notify from specific zones
    # zones:
    #   - camera: garage
    #     zone: driveway

